### PR TITLE
[#7] Clear search input after Brewery selection

### PR DESCRIPTION
**Pull request by loiscodes**
Clear text input after website selection

### CODE REVIEW

**Comment by loiscodes** [comment]
Let me know if this satisfies the issue

**Comment by MStewGT** [comment]
Hi @loiscodes, thanks for working on this one. It looks like you are close! It appears that the input field is being cleared, but when you click on a website link. I think it would work best if we cleared the field when selecting the input field itself. This makes it so that I can search for say Denver and click go, scroll through the list, decide to search for Chicago instead, and it clears the box so I don't have to manually remove the Denver text. I think we can accomplish this by just moving your "onClick" to the input box code:
```javascript
<input
  value={locData}
  onChange={onLocChange}
/>
```

**Comment by loiscodes** [comment]
Got ya! Updated branch

**Comment by MStewGT** [comment]
Perfect, thanks for your contribution! Your change is live now: https://findmebeer.app

**Pull request merged**
