### PR TITLE
Empty state error

### PR DESCRIPTION
**Pull request by lnfnunes**
This PR fixes the issue #6.

**I've also taken the opportunity to:**
- Fix some invalid `class` attributes.
- Change the page and cards layout and responsive design.

Hope you enjoy it! :v:

### CODE REVIEW

**Comment by MStewGT** [comment]
Hi @lnfnunes, I like what you are doing here with the more responsive layout. It looks good and seems to work well until 4 columns or more which for me appears to start around 1310px width.
image

**Comment by MStewGT** [comment]
FYI, I opened a new Issue for this #11

**Comment by lnfnunes** [comment]
Thank you @MStewGT.
Should I fix that in this same PR or we should merge it and open a new one for the issue #11 ?

About the fix, I think we could set a max-width to the page. But if you prefer I can try to fix the 4+ columns...

**Comment by MStewGT** [comment]
@lnfnunes Merged this one. Feel free to open a new PR on #11 with whatever method you think looks best.

**Pull request merged**
